"""tickets

Revision ID: 0745ccb8b8fb
Revises: a2d03015e119
Create Date: 2025-02-03 07:43:37.729118

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0745ccb8b8fb'
down_revision: Union[str, None] = 'a2d03015e119'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('created_by_admin_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_tickets_created_by_admin_id'), 'tickets', ['created_by_admin_id'], unique=False)
    op.create_foreign_key(None, 'tickets', 'admin', ['created_by_admin_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.drop_index(op.f('ix_tickets_created_by_admin_id'), table_name='tickets')
    op.drop_column('tickets', 'created_by_admin_id')
    # ### end Alembic commands ###
