"""Subscription Plans

Revision ID: 13b4805199e1
Revises: b2e5c43df413
Create Date: 2024-12-08 19:08:44.255107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13b4805199e1'
down_revision: Union[str, None] = 'b2e5c43df413'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('md_subscription_plans', sa.Column('amount', sa.Float(), nullable=True, comment='Amount in INR'))
    op.add_column('md_subscription_plans', sa.Column('validity', sa.Integer(), nullable=True, comment='Validity in Days'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('md_subscription_plans', 'validity')
    op.drop_column('md_subscription_plans', 'amount')
    # ### end Alembic commands ###
