"""sgdfgds

Revision ID: 1d50ae2eb583
Revises: 4df5031e62fa
Create Date: 2025-01-05 11:22:58.020048

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '1d50ae2eb583'
down_revision: Union[str, None] = '4df5031e62fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('application_details', 'total_obligation_amount_per_month',
               existing_type=mysql.FLOAT(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)
    op.alter_column('subscriptions', 'payment_amount',
               existing_type=mysql.FLOAT(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subscriptions', 'payment_amount',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=mysql.FLOAT(),
               existing_nullable=True)
    op.alter_column('application_details', 'total_obligation_amount_per_month',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=mysql.FLOAT(),
               existing_nullable=True)
    # ### end Alembic commands ###
