"""Service configuration

Revision ID: 1e724259e35d
Revises: d58240fe2ffc
Create Date: 2024-11-14 06:38:21.925812

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e724259e35d'
down_revision: Union[str, None] = 'd58240fe2ffc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('agent_id', sa.Integer(), nullable=True))
    op.add_column('customers', sa.Column('salesman_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'salesman_id')
    op.drop_column('customers', 'agent_id')
    # ### end Alembic commands ###
