"""agent fields added

Revision ID: 2133e114d73e
Revises: 3f3515e1cad3
Create Date: 2024-11-27 07:20:32.740448

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2133e114d73e'
down_revision: Union[str, None] = '3f3515e1cad3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin', sa.Column('passport', sa.Text(), nullable=True))
    op.add_column('admin', sa.Column('aadhaar_card', sa.Text(), nullable=True))
    op.add_column('admin', sa.Column('selfie', sa.Text(), nullable=True))
    op.add_column('admin', sa.Column('present_address', sa.Text(), nullable=True))
    op.add_column('admin', sa.Column('present_occupation', sa.Text(), nullable=True))
    op.add_column('admin', sa.Column('employer_name', sa.Text(), nullable=True))
    op.add_column('admin', sa.Column('qualification', sa.Text(), nullable=True))
    op.add_column('admin', sa.Column('account_holder_name', sa.Text(), nullable=True))
    op.add_column('admin', sa.Column('bank_name', sa.Text(), nullable=True))
    op.add_column('admin', sa.Column('bank_account_number', sa.Text(), nullable=True))
    op.add_column('admin', sa.Column('ifsc_code', sa.Text(), nullable=True))
    op.add_column('admin', sa.Column('upload_check', sa.Text(), nullable=True))
    op.add_column('admin', sa.Column('referrals', sa.Text(), nullable=True))
    op.alter_column('application_details', 'loanAmount',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('application_details', 'loanAmount',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.drop_column('admin', 'referrals')
    op.drop_column('admin', 'upload_check')
    op.drop_column('admin', 'ifsc_code')
    op.drop_column('admin', 'bank_account_number')
    op.drop_column('admin', 'bank_name')
    op.drop_column('admin', 'account_holder_name')
    op.drop_column('admin', 'qualification')
    op.drop_column('admin', 'employer_name')
    op.drop_column('admin', 'present_occupation')
    op.drop_column('admin', 'present_address')
    op.drop_column('admin', 'selfie')
    op.drop_column('admin', 'aadhaar_card')
    op.drop_column('admin', 'passport')
    # ### end Alembic commands ###
