"""Service configuration

Revision ID: 2d072c590e7d
Revises: 7634213ac996
Create Date: 2024-11-14 17:02:07.078299

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2d072c590e7d'
down_revision: Union[str, None] = '7634213ac996'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application_details', sa.Column('lastYearITRamount', sa.Float(), nullable=True))
    op.add_column('application_details', sa.Column('presentYearITRamount', sa.Float(), nullable=True))
    op.alter_column('application_details', 'loanAmount',
               existing_type=mysql.FLOAT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('application_details', 'loanAmount',
               existing_type=mysql.FLOAT(),
               nullable=False)
    op.drop_column('application_details', 'presentYearITRamount')
    op.drop_column('application_details', 'lastYearITRamount')
    # ### end Alembic commands ###
