"""sfsdf

Revision ID: 49c06ef3dda4
Revises: c52bb5cf61d6
Create Date: 2024-12-04 22:19:20.473368

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '49c06ef3dda4'
down_revision: Union[str, None] = 'c52bb5cf61d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('application_details', 'loanAmount',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.add_column('enquiries', sa.Column('followupdate', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_md_ifsc_codes_BANK'), 'md_ifsc_codes', ['BANK'], unique=False)
    op.create_index(op.f('ix_md_ifsc_codes_BRANCH'), 'md_ifsc_codes', ['BRANCH'], unique=False)
    op.create_index(op.f('ix_md_ifsc_codes_CITY1'), 'md_ifsc_codes', ['CITY1'], unique=False)
    op.create_index(op.f('ix_md_ifsc_codes_CITY2'), 'md_ifsc_codes', ['CITY2'], unique=False)
    op.create_index(op.f('ix_md_ifsc_codes_IFSC'), 'md_ifsc_codes', ['IFSC'], unique=False)
    op.create_index(op.f('ix_md_ifsc_codes_STATE'), 'md_ifsc_codes', ['STATE'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_md_ifsc_codes_STATE'), table_name='md_ifsc_codes')
    op.drop_index(op.f('ix_md_ifsc_codes_IFSC'), table_name='md_ifsc_codes')
    op.drop_index(op.f('ix_md_ifsc_codes_CITY2'), table_name='md_ifsc_codes')
    op.drop_index(op.f('ix_md_ifsc_codes_CITY1'), table_name='md_ifsc_codes')
    op.drop_index(op.f('ix_md_ifsc_codes_BRANCH'), table_name='md_ifsc_codes')
    op.drop_index(op.f('ix_md_ifsc_codes_BANK'), table_name='md_ifsc_codes')
    op.drop_column('enquiries', 'followupdate')
    op.alter_column('application_details', 'loanAmount',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    # ### end Alembic commands ###
