"""sgdfgds

Revision ID: 4c8b249e02f4
Revises: 5071d7c8e20a
Create Date: 2025-01-05 11:12:19.108046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '4c8b249e02f4'
down_revision: Union[str, None] = '5071d7c8e20a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('customer_details', 'last_year_itr',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               type_=sa.String(length=55),
               existing_nullable=True)
    op.alter_column('customer_details', 'current_year_itr',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.String(length=55),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('customer_details', 'current_year_itr',
               existing_type=sa.String(length=55),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=True)
    op.alter_column('customer_details', 'last_year_itr',
               existing_type=sa.String(length=55),
               type_=mysql.DECIMAL(precision=10, scale=2),
               existing_nullable=True)
    # ### end Alembic commands ###
