"""sgdfgds

Revision ID: 5071d7c8e20a
Revises: 55fbb8901551
Create Date: 2025-01-05 11:09:52.199679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '5071d7c8e20a'
down_revision: Union[str, None] = '55fbb8901551'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('customer_details', 'totalExperience',
               existing_type=mysql.FLOAT(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_comment='Total work experience in years (e.g., 1.5 for one and a half years)',
               existing_nullable=True)
    op.alter_column('customer_details', 'present_organization_years',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)
    op.alter_column('customer_details', 'grossSalary',
               existing_type=mysql.FLOAT(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_comment='gross salary',
               existing_nullable=True)
    op.alter_column('customer_details', 'netSalary',
               existing_type=mysql.FLOAT(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_comment='net salary',
               existing_nullable=True)
    op.alter_column('customer_details', 'obligations_per_month',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)
    op.alter_column('customer_details', 'number_of_years',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)
    op.alter_column('customer_details', 'last_year_turnover_amount',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)
    op.alter_column('customer_details', 'last_year_itr',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)
    op.alter_column('customer_details', 'lastYearITRamount',
               existing_type=mysql.FLOAT(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)
    op.alter_column('customer_details', 'current_year_turnover_amount',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)
    op.alter_column('customer_details', 'presentYearITRamount',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)
    op.alter_column('customer_details', 'avg_income_per_month',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)
    op.alter_column('customer_details', 'total_obligation_amount_per_month',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('customer_details', 'total_obligation_amount_per_month',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=True)
    op.alter_column('customer_details', 'avg_income_per_month',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=True)
    op.alter_column('customer_details', 'presentYearITRamount',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=True)
    op.alter_column('customer_details', 'current_year_turnover_amount',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=True)
    op.alter_column('customer_details', 'lastYearITRamount',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=mysql.FLOAT(),
               existing_nullable=True)
    op.alter_column('customer_details', 'last_year_itr',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=True)
    op.alter_column('customer_details', 'last_year_turnover_amount',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=True)
    op.alter_column('customer_details', 'number_of_years',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=True)
    op.alter_column('customer_details', 'obligations_per_month',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=True)
    op.alter_column('customer_details', 'netSalary',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=mysql.FLOAT(),
               existing_comment='net salary',
               existing_nullable=True)
    op.alter_column('customer_details', 'grossSalary',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=mysql.FLOAT(),
               existing_comment='gross salary',
               existing_nullable=True)
    op.alter_column('customer_details', 'present_organization_years',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=True)
    op.alter_column('customer_details', 'totalExperience',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=mysql.FLOAT(),
               existing_comment='Total work experience in years (e.g., 1.5 for one and a half years)',
               existing_nullable=True)
    # ### end Alembic commands ###
