"""payments

Revision ID: 5942c5b9ab56
Revises: cd45e668b7e5
Create Date: 2024-12-15 17:33:31.126580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5942c5b9ab56'
down_revision: Union[str, None] = 'cd45e668b7e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('invoice_id', sa.String(length=100), nullable=True))
    op.add_column('subscriptions', sa.Column('payment_link', sa.Text(), nullable=True))
    op.create_index(op.f('ix_subscriptions_invoice_id'), 'subscriptions', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_payment_link'), 'subscriptions', ['payment_link'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subscriptions_payment_link'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_invoice_id'), table_name='subscriptions')
    op.drop_column('subscriptions', 'payment_link')
    op.drop_column('subscriptions', 'invoice_id')
    # ### end Alembic commands ###
