"""enquiry model added

Revision ID: 6ac0c592c91c
Revises: 75ba6ebf3245
Create Date: 2024-11-23 12:50:02.657372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '6ac0c592c91c'
down_revision: Union[str, None] = '75ba6ebf3245'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('application_details', 'loanAmount',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.alter_column('enquiries', 'tenant_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.create_foreign_key(None, 'enquiries', 'md_service_types', ['tenant_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'enquiries', type_='foreignkey')
    op.alter_column('enquiries', 'tenant_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('application_details', 'loanAmount',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    # ### end Alembic commands ###
