"""pin cde added

Revision ID: 79b20eac7a9f
Revises: ed4d9bf97a64
Create Date: 2024-12-02 08:28:19.763434

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '79b20eac7a9f'
down_revision: Union[str, None] = 'ed4d9bf97a64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin', sa.Column('pincode', sa.Text(), nullable=True))
    op.alter_column('application_details', 'loanAmount',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('application_details', 'loanAmount',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.drop_column('admin', 'pincode')
    # ### end Alembic commands ###
