"""tickets

Revision ID: a5f5165c7f19
Revises: 61ee1ec4a491
Create Date: 2025-02-03 07:26:28.149137

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5f5165c7f19'
down_revision: Union[str, None] = '61ee1ec4a491'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket_comments', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_ticket_comments_user_id'), 'ticket_comments', ['user_id'], unique=False)
    op.create_foreign_key(None, 'ticket_comments', 'customers', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ticket_comments', type_='foreignkey')
    op.drop_index(op.f('ix_ticket_comments_user_id'), table_name='ticket_comments')
    op.drop_column('ticket_comments', 'user_id')
    # ### end Alembic commands ###
