"""Add User

Revision ID: af6a7aa57807
Revises: 568fb47741de
Create Date: 2024-11-09 10:58:47.975054

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af6a7aa57807'
down_revision: Union[str, None] = '568fb47741de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_user_details',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('admin_user_id', sa.Integer(), nullable=True),
    sa.Column('pancard_or_passport', sa.String(length=50), nullable=True),
    sa.Column('aadhaar_card', sa.String(length=50), nullable=True),
    sa.Column('present_address', sa.Text(), nullable=True),
    sa.Column('present_occupation', sa.String(length=60), nullable=True),
    sa.Column('employer_name', sa.String(length=60), nullable=True),
    sa.Column('qualification', sa.String(length=60), nullable=True),
    sa.Column('account_holder_name', sa.String(length=60), nullable=True),
    sa.Column('bank_name', sa.String(length=60), nullable=True),
    sa.Column('bank_account_number', sa.String(length=60), nullable=True),
    sa.Column('ifsc_code', sa.String(length=60), nullable=True),
    sa.Column('empty_check', sa.String(length=60), nullable=True),
    sa.Column('referral_name_one', sa.String(length=60), nullable=True),
    sa.Column('referral_mobile_number_one', sa.String(length=15), nullable=True),
    sa.Column('referral_address_one', sa.Text(), nullable=True),
    sa.Column('referral_name_two', sa.String(length=60), nullable=True),
    sa.Column('referral_mobile_number_two', sa.String(length=15), nullable=True),
    sa.Column('referral_address_two', sa.Text(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['admin_user_id'], ['admin.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('admin', sa.Column('alternate_mobile_no', sa.String(length=15), nullable=True))
    op.add_column('admin', sa.Column('experience', sa.Float(), nullable=True))
    op.add_column('admin', sa.Column('profile_image', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admin', 'profile_image')
    op.drop_column('admin', 'experience')
    op.drop_column('admin', 'alternate_mobile_no')
    op.drop_table('admin_user_details')
    # ### end Alembic commands ###
