"""ifsc codes

Revision ID: c52bb5cf61d6
Revises: 0344bdc67ff4
Create Date: 2024-12-03 21:22:40.154091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c52bb5cf61d6'
down_revision: Union[str, None] = '0344bdc67ff4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('md_ifsc_codes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('BANK', sa.String(length=50), nullable=True),
    sa.Column('IFSC', sa.String(length=50), nullable=True),
    sa.Column('BRANCH', sa.String(length=50), nullable=True),
    sa.Column('ADDRESS', sa.Text(), nullable=True),
    sa.Column('CITY1', sa.String(length=100), nullable=True),
    sa.Column('CITY2', sa.String(length=100), nullable=True),
    sa.Column('STATE', sa.String(length=100), nullable=True),
    sa.Column('STD_CODE', sa.String(length=100), nullable=True),
    sa.Column('PHONE', sa.String(length=100), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('application_details', 'loanAmount',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('application_details', 'loanAmount',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.drop_table('md_ifsc_codes')
    # ### end Alembic commands ###
