"""changes

Revision ID: cd45e668b7e5
Revises: cf077083ea3b
Create Date: 2024-12-11 12:01:53.767250

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd45e668b7e5'
down_revision: Union[str, None] = 'cf077083ea3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('pan_card_number', sa.String(length=55), nullable=True))
    op.add_column('customers', sa.Column('aadhaar_card_number', sa.String(length=55), nullable=True))
    op.add_column('customers', sa.Column('nominee', sa.String(length=100), nullable=True))
    op.add_column('customers', sa.Column('relation_with_nominee', sa.String(length=200), nullable=True))
    op.add_column('customers', sa.Column('aadhaar_card', sa.Text(), nullable=True))
    op.add_column('customers', sa.Column('canceled_cheque', sa.Text(), nullable=True))
    op.add_column('customers', sa.Column('selfie', sa.Text(), nullable=True))
    op.add_column('customers', sa.Column('reference_id', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'reference_id')
    op.drop_column('customers', 'selfie')
    op.drop_column('customers', 'canceled_cheque')
    op.drop_column('customers', 'aadhaar_card')
    op.drop_column('customers', 'relation_with_nominee')
    op.drop_column('customers', 'nominee')
    op.drop_column('customers', 'aadhaar_card_number')
    op.drop_column('customers', 'pan_card_number')
    # ### end Alembic commands ###
