"""payments

Revision ID: cf077083ea3b
Revises: e2bb8b379c9d
Create Date: 2024-12-10 16:05:28.456557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf077083ea3b'
down_revision: Union[str, None] = 'e2bb8b379c9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('tenant_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscriptions', 'tenant_id')
    # ### end Alembic commands ###
