"""Subscription plan

Revision ID: d1d3dd271f2b
Revises: 17565b35f148
Create Date: 2024-11-13 18:37:50.521670

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd1d3dd271f2b'
down_revision: Union[str, None] = '17565b35f148'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('md_subscription_plans',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('application_details', sa.Column('md_subscription_plan_id', sa.Integer(), nullable=True))
    op.add_column('application_details', sa.Column('subscription_history', sa.Text(), nullable=True, comment='History of subscription'))
    op.add_column('application_details', sa.Column('companyName', sa.String(length=55), nullable=True))
    op.add_column('application_details', sa.Column('totalExperience', sa.Float(), nullable=True, comment='Total work experience in years (e.g., 1.5 for one and a half years)'))
    op.add_column('application_details', sa.Column('workLocation', sa.String(length=55), nullable=True))
    op.add_column('application_details', sa.Column('grossSalary', sa.Float(), nullable=True, comment='gross salary'))
    op.add_column('application_details', sa.Column('netSalary', sa.Float(), nullable=True, comment='net salary'))
    op.add_column('application_details', sa.Column('otherIncome', sa.String(length=6), nullable=True, comment='net salary'))
    op.add_column('application_details', sa.Column('Obligations', sa.String(length=6), nullable=True, comment='Obligations'))
    op.add_column('application_details', sa.Column('other_income_list', sa.Text(), nullable=True, comment="JSON stringified list of income sources, e.g., [{'income_type':'job','income':20},{'income_type':'rental','income':10}]"))
    op.create_foreign_key(None, 'application_details', 'md_subscription_plans', ['md_subscription_plan_id'], ['id'])
    op.drop_column('application_details', 'company_name')
    op.drop_column('application_details', 'net_salary')
    op.drop_column('application_details', 'total_experience')
    op.drop_column('application_details', 'work_location')
    op.drop_column('application_details', 'obligation')
    op.drop_column('application_details', 'other_income')
    op.drop_column('application_details', 'gross_salary')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application_details', sa.Column('gross_salary', mysql.FLOAT(), nullable=True, comment='gross salary'))
    op.add_column('application_details', sa.Column('other_income', mysql.TEXT(), nullable=True, comment="JSON stringified list of income sources, e.g., [{'income_type':'job','income':20},{'income_type':'rental','income':10}]"))
    op.add_column('application_details', sa.Column('obligation', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('application_details', sa.Column('work_location', mysql.VARCHAR(length=55), nullable=True))
    op.add_column('application_details', sa.Column('total_experience', mysql.FLOAT(), nullable=True, comment='Total work experience in years (e.g., 1.5 for one and a half years)'))
    op.add_column('application_details', sa.Column('net_salary', mysql.FLOAT(), nullable=True, comment='net salary'))
    op.add_column('application_details', sa.Column('company_name', mysql.VARCHAR(length=55), nullable=True))
    op.drop_constraint(None, 'application_details', type_='foreignkey')
    op.drop_column('application_details', 'other_income_list')
    op.drop_column('application_details', 'Obligations')
    op.drop_column('application_details', 'otherIncome')
    op.drop_column('application_details', 'netSalary')
    op.drop_column('application_details', 'grossSalary')
    op.drop_column('application_details', 'workLocation')
    op.drop_column('application_details', 'totalExperience')
    op.drop_column('application_details', 'companyName')
    op.drop_column('application_details', 'subscription_history')
    op.drop_column('application_details', 'md_subscription_plan_id')
    op.drop_table('md_subscription_plans')
    # ### end Alembic commands ###
