"""user address

Revision ID: d32d1eadfa0e
Revises: b56778865468
Create Date: 2024-12-01 12:26:19.244517

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd32d1eadfa0e'
down_revision: Union[str, None] = 'b56778865468'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin', sa.Column('country_id', sa.Integer(), nullable=True))
    op.add_column('admin', sa.Column('state_id', sa.Integer(), nullable=True))
    op.add_column('admin', sa.Column('location_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'admin', 'md_states', ['state_id'], ['id'])
    op.create_foreign_key(None, 'admin', 'md_countries', ['country_id'], ['id'])
    op.create_foreign_key(None, 'admin', 'md_locations', ['location_id'], ['id'])
    op.alter_column('application_details', 'loanAmount',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('application_details', 'loanAmount',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.drop_constraint(None, 'admin', type_='foreignkey')
    op.drop_constraint(None, 'admin', type_='foreignkey')
    op.drop_constraint(None, 'admin', type_='foreignkey')
    op.drop_column('admin', 'location_id')
    op.drop_column('admin', 'state_id')
    op.drop_column('admin', 'country_id')
    # ### end Alembic commands ###
