"""Payment intigration

Revision ID: e2bb8b379c9d
Revises: 13b4805199e1
Create Date: 2024-12-10 10:36:02.936156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e2bb8b379c9d'
down_revision: Union[str, None] = '13b4805199e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('plan_id', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('payment_status', sa.String(length=100), nullable=True),
    sa.Column('payment_amount', sa.Float(), nullable=True),
    sa.Column('razorpay_order_id', sa.String(length=100), nullable=True),
    sa.Column('razorpay_payment_id', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True, comment='Is status ==True plan is active, if False == plan inactive'),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['md_subscription_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscriptions_id'), 'subscriptions', ['id'], unique=False)
    op.create_index(op.f('ix_subscriptions_razorpay_order_id'), 'subscriptions', ['razorpay_order_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_razorpay_payment_id'), 'subscriptions', ['razorpay_payment_id'], unique=False)
    op.add_column('customers', sa.Column('current_plan_id', sa.Integer(), nullable=True))
    op.drop_constraint('customers_ibfk_2', 'customers', type_='foreignkey')
    op.create_foreign_key(None, 'customers', 'md_subscription_plans', ['current_plan_id'], ['id'])
    op.drop_column('customers', 'md_subscription_plan_id')
    op.drop_column('customers', 'subscription_history')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('subscription_history', mysql.TEXT(), nullable=True, comment='History of subscription'))
    op.add_column('customers', sa.Column('md_subscription_plan_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'customers', type_='foreignkey')
    op.create_foreign_key('customers_ibfk_2', 'customers', 'md_subscription_plans', ['md_subscription_plan_id'], ['id'])
    op.drop_column('customers', 'current_plan_id')
    op.drop_index(op.f('ix_subscriptions_razorpay_payment_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_razorpay_order_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    # ### end Alembic commands ###
