"""Loan model Changes

Revision ID: e5b99d761fa3
Revises: af6a7aa57807
Create Date: 2024-11-12 18:27:59.181509

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5b99d761fa3'
down_revision: Union[str, None] = 'af6a7aa57807'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application_details', sa.Column('service_type_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'application_details', 'md_service_types', ['service_type_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'application_details', type_='foreignkey')
    op.drop_column('application_details', 'service_type_id')
    # ### end Alembic commands ###
