"""enquiry model added

Revision ID: e64c45eca5f2
Revises: 6ac0c592c91c
Create Date: 2024-11-23 12:52:46.532025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e64c45eca5f2'
down_revision: Union[str, None] = '6ac0c592c91c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('application_details', 'loanAmount',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.drop_constraint('enquiries_ibfk_3', 'enquiries', type_='foreignkey')
    op.create_foreign_key(None, 'enquiries', 'tenants', ['tenant_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'enquiries', type_='foreignkey')
    op.create_foreign_key('enquiries_ibfk_3', 'enquiries', 'md_service_types', ['tenant_id'], ['id'])
    op.alter_column('application_details', 'loanAmount',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    # ### end Alembic commands ###
