"""dhsdj

Revision ID: ec09473974a5
Revises: 1c22ec704eb9
Create Date: 2024-11-15 21:47:38.474094

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ec09473974a5'
down_revision: Union[str, None] = '1c22ec704eb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('application_details', 'loanAmount',
               existing_type=mysql.FLOAT(),
               type_=sa.String(length=50),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('application_details', 'loanAmount',
               existing_type=sa.String(length=50),
               type_=mysql.FLOAT(),
               nullable=False)
    # ### end Alembic commands ###
