"""Subscription plan

Revision ID: f23f623cd5e8
Revises: d1d3dd271f2b
Create Date: 2024-11-13 19:00:29.442978

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f23f623cd5e8'
down_revision: Union[str, None] = 'd1d3dd271f2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('application_details_ibfk_9', 'application_details', type_='foreignkey')
    op.drop_column('application_details', 'md_subscription_plan_id')
    op.drop_column('application_details', 'subscription_history')
    op.add_column('customers', sa.Column('md_subscription_plan_id', sa.Integer(), nullable=True))
    op.add_column('customers', sa.Column('subscription_history', sa.Text(), nullable=True, comment='History of subscription'))
    op.create_foreign_key(None, 'customers', 'md_subscription_plans', ['md_subscription_plan_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'customers', type_='foreignkey')
    op.drop_column('customers', 'subscription_history')
    op.drop_column('customers', 'md_subscription_plan_id')
    op.add_column('application_details', sa.Column('subscription_history', mysql.TEXT(), nullable=True, comment='History of subscription'))
    op.add_column('application_details', sa.Column('md_subscription_plan_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('application_details_ibfk_9', 'application_details', 'md_subscription_plans', ['md_subscription_plan_id'], ['id'])
    # ### end Alembic commands ###
